"""
Phantom Recon — WAF & CDN Detector and Origin IP Discovery Engine.

Detects Web Application Firewalls (WAF) and Cloud CDNs (Cloudflare, Akamai,
AWS CloudFront, Imperva, Fastly, Sucuri, F5 BIG-IP, ModSecurity, etc.).
Prevents false-alarm scanning against WAF edge nodes and audits for
unprotected origin server IP leakage via DNS records, SPF, MX, and unproxied subdomains.

⚠️ DISCLAIMER: For authorized security testing only.
"""

from dataclasses import dataclass
from datetime import datetime
import ipaddress
import re
import socket
from typing import Any, Optional
from urllib.parse import urlparse

import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

from phantom_recon.utils.logger import get_logger, console
from phantom_recon.utils.validators import validate_ip, validate_domain, validate_url

logger = get_logger(__name__)

# Known Cloud WAF / CDN IPv4 CIDR blocks
WAF_CIDR_BLOCKS: dict[str, list[str]] = {
    "Cloudflare": [
        "173.245.48.0/20",
        "103.21.244.0/22",
        "103.22.200.0/22",
        "103.31.4.0/22",
        "141.101.64.0/18",
        "108.162.192.0/18",
        "190.93.240.0/20",
        "188.114.96.0/20",
        "197.234.240.0/22",
        "198.41.128.0/17",
        "162.158.0.0/15",
        "104.16.0.0/13",
        "104.24.0.0/14",
        "172.64.0.0/13",
        "131.0.72.0/22",
    ],
    "Fastly": [
        "151.101.0.0/16",
        "199.232.0.0/16",
        "146.75.0.0/16",
    ],
    "Imperva / Incapsula": [
        "199.83.128.0/21",
        "198.143.32.0/19",
        "149.126.72.0/21",
        "103.28.248.0/22",
        "185.11.124.0/22",
        "192.230.64.0/18",
        "107.154.0.0/16",
        "45.64.64.0/22",
    ],
    "Sucuri": [
        "192.88.134.0/23",
        "185.93.228.0/22",
        "66.248.200.0/22",
        "208.109.0.0/22",
    ],
    "Akamai": [
        "23.32.0.0/11",
        "23.64.0.0/14",
        "104.64.0.0/10",
        "184.24.0.0/13",
        "2.16.0.0/13",
        "23.0.0.0/12",
    ],
}

# Compiled network structures for O(1) IP lookup
_COMPILED_WAF_NETWORKS: list[tuple[str, Any]] = []
for provider, cidrs in WAF_CIDR_BLOCKS.items():
    for cidr in cidrs:
        try:
            _COMPILED_WAF_NETWORKS.append((provider, ipaddress.ip_network(cidr, strict=False)))
        except ValueError:
            pass

# WAF HTTP Fingerprint Signatures
WAF_HTTP_SIGNATURES: list[dict[str, Any]] = [
    {
        "name": "Cloudflare",
        "headers": [
            ("server", r"cloudflare"),
            ("cf-ray", r".+"),
            ("cf-cache-status", r".+"),
        ],
        "cookies": [r"__cfduid", r"cf_clearance"],
        "body_patterns": [r"attention required! \| cloudflare", r"ray id:"],
    },
    {
        "name": "AWS CloudFront / AWS WAF",
        "headers": [
            ("via", r"cloudfront\.net"),
            ("x-amz-cf-id", r".+"),
            ("x-amz-cf-pop", r".+"),
            ("server", r"cloudfront"),
        ],
        "body_patterns": [r"generated by cloudfront", r"request blocked by aws waf"],
    },
    {
        "name": "Akamai / Kona Site Defender",
        "headers": [
            ("server", r"akamaighost"),
            ("x-akamai-transformed", r".+"),
            ("x-akamai-staging", r".+"),
        ],
        "body_patterns": [r"the requested url was not recognized by akamai", r"reference #\d+\.\w+"],
    },
    {
        "name": "Imperva / Incapsula",
        "headers": [
            ("x-cdn", r"incapsula"),
            ("x-iinfo", r".+"),
        ],
        "cookies": [r"visid_incap", r"incap_ses"],
        "body_patterns": [r"incapsula incident id", r"powered by incapsula"],
    },
    {
        "name": "Fastly",
        "headers": [
            ("x-fastly-request-id", r".+"),
            ("fastly-debug-digest", r".+"),
            ("server", r"fastly"),
        ],
        "body_patterns": [r"fastly error: unknown domain"],
    },
    {
        "name": "Sucuri CloudProxy",
        "headers": [
            ("x-sucuri-id", r".+"),
            ("x-sucuri-cache", r".+"),
            ("server", r"sucuri/cloudproxy"),
        ],
        "body_patterns": [r"sucuri website firewall", r"access denied - sucuri website firewall"],
    },
    {
        "name": "F5 BIG-IP / ASM",
        "headers": [
            ("server", r"big-ip"),
            ("x-wa-info", r".+"),
        ],
        "cookies": [r"^ts[0-9a-f]{6,}", r"^bigipserver"],
        "body_patterns": [r"the requested url was rejected\. please consult with your administrator"],
    },
    {
        "name": "ModSecurity / OWASP CRS",
        "headers": [
            ("server", r"mod_security"),
            ("server", r"noyb"),
        ],
        "body_patterns": [r"this error was generated by mod_security"],
    },
    {
        "name": "Microsoft Azure Front Door / App Gateway",
        "headers": [
            ("x-azure-ref", r".+"),
            ("x-azure-fdid", r".+"),
        ],
        "body_patterns": [r"azure front door", r"our services aren't available right now"],
    },
    {
        "name": "Barracuda WAF",
        "headers": [
            ("server", r"barra"),
        ],
        "cookies": [r"^barra_counter_session"],
        "body_patterns": [r"you have been blocked by the barracuda web application firewall"],
    },
]


@dataclass
class OriginCandidate:
    """Represents a potential unproxied backend origin IP candidate."""
    ip: str
    hostname: str
    source: str                 # "MX Record", "SPF ip4", "Subdomain direct.domain.com"
    is_waf_ip: bool = False
    waf_provider: str = ""
    reaches_app: bool = False   # True if HTTP Host check returns matching content
    evidence: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "ip": self.ip,
            "hostname": self.hostname,
            "source": self.source,
            "is_waf_ip": self.is_waf_ip,
            "waf_provider": self.waf_provider,
            "reaches_app": self.reaches_app,
            "evidence": self.evidence,
        }


def is_routable_public_ip(ip: str) -> bool:
    """Validate that IP is not 0.0.0.0, loopback, link-local, multicast, or private RFC 1918."""
    try:
        addr = ipaddress.ip_address(ip)
        if addr.version != 4:
            return False
        if addr.is_unspecified or addr.is_loopback or addr.is_link_local or addr.is_multicast:
            return False
        if str(addr).startswith("0."):
            return False
        for net in (
            ipaddress.ip_network("10.0.0.0/8"),
            ipaddress.ip_network("172.16.0.0/12"),
            ipaddress.ip_network("192.168.0.0/16"),
        ):
            if addr in net:
                return False
        return True
    except ValueError:
        return False


class WAFDetector:
    """
    Web Application Firewall (WAF) & Cloud CDN Detector.
    
    Identifies cloud security edge proxies and audits for origin IP exposure.
    Prevents false-positive port scans against Cloudflare/Akamai infrastructure
    and flags direct origin reachability.
    """

    def __init__(self, target: str, timeout: float = 6.0):
        """
        Initialize WAF detector.

        Args:
            target: Target domain, IP, or URL.
            timeout: Request timeout in seconds.
        """
        self.target = target.strip()
        self.timeout = timeout
        self.session = requests.Session()
        self.session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 PhantomRecon/1.5.2",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        })
        self.session.verify = False

        # Extract domain / IP / URL components
        self.domain = self._extract_domain(target)
        self.url = self._normalize_url(target)

    def _extract_domain(self, target: str) -> str:
        """Extract clean hostname/domain from string."""
        if target.startswith("http://") or target.startswith("https://"):
            parsed = urlparse(target)
            return parsed.hostname or target
        if ":" in target and not target.count(":") > 1:  # host:port
            return target.split(":")[0]
        return target

    def _normalize_url(self, target: str) -> str:
        """Build standard HTTP URL from target."""
        if target.startswith("http://") or target.startswith("https://"):
            return target
        return f"https://{target}"

    @staticmethod
    def is_ip_in_waf_cidr(ip: str) -> tuple[bool, str]:
        """
        Check if an IPv4 address belongs to a known cloud WAF/CDN provider network.

        Args:
            ip: IPv4 address string.

        Returns:
            Tuple of (is_waf, provider_name).
        """
        if not validate_ip(ip):
            return False, ""
        try:
            ip_obj = ipaddress.ip_address(ip)
            for provider, network in _COMPILED_WAF_NETWORKS:
                if ip_obj in network:
                    return True, provider
        except ValueError:
            pass
        return False, ""

    def resolve_target_ips(self) -> list[str]:
        """Resolve target domain to IPv4 addresses."""
        if validate_ip(self.domain):
            return [self.domain]
        ips = []
        try:
            addr_info = socket.getaddrinfo(self.domain, None, socket.AF_INET)
            for item in addr_info:
                ip = item[4][0]
                if ip not in ips:
                    ips.append(ip)
        except socket.gaierror:
            pass
        return ips

    def detect_waf(self) -> dict[str, Any]:
        """
        Detect whether target is protected by a WAF or Cloud CDN.

        Returns:
            Dictionary containing WAF detection findings, provider, and evidence.
        """
        logger.info(f"Auditing target [bold magenta]{self.target}[/bold magenta] for WAF/CDN...")
        resolved_ips = self.resolve_target_ips()
        waf_detected = False
        waf_name = "None"
        matched_indicators: list[str] = []

        # 1. Zero-request IP CIDR matching
        for ip in resolved_ips:
            is_waf, provider = self.is_ip_in_waf_cidr(ip)
            if is_waf:
                waf_detected = True
                waf_name = provider
                indicator = f"Resolved IP {ip} belongs to {provider} proxy network."
                if indicator not in matched_indicators:
                    matched_indicators.append(indicator)

        # 2. HTTP Banner & Fingerprint Inspection
        try:
            resp = self.session.get(self.url, timeout=self.timeout, allow_redirects=True)
            headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
            body_lower = resp.text.lower()[:20000]
            cookie_names = [c.name.lower() for c in resp.cookies]

            for sig in WAF_HTTP_SIGNATURES:
                provider_name = sig["name"]

                # Match response headers
                for header_key, pattern in sig.get("headers", []):
                    if header_key in headers_lower and re.search(pattern, headers_lower[header_key]):
                        waf_detected = True
                        waf_name = provider_name
                        matched_indicators.append(
                            f"Header '{header_key}: {resp.headers.get(header_key)}' matches {provider_name} signature."
                        )

                # Match cookies
                for cookie_pattern in sig.get("cookies", []):
                    for cname in cookie_names:
                        if re.search(cookie_pattern, cname):
                            waf_detected = True
                            waf_name = provider_name
                            matched_indicators.append(
                                f"Cookie '{cname}' matches {provider_name} WAF session cookie signature."
                            )

                # Match response body
                for body_pat in sig.get("body_patterns", []):
                    if re.search(body_pat, body_lower):
                        waf_detected = True
                        waf_name = provider_name
                        matched_indicators.append(
                            f"Response body matches {provider_name} security challenge signature."
                        )

        except requests.RequestException as e:
            logger.debug(f"HTTP WAF probe request failed: {e}")

        # Construct comprehensive result
        warning_msg = ""
        if waf_detected:
            warning_msg = (
                f"⚠️ Target is fronted by {waf_name} CDN/WAF. "
                f"Direct port scans on resolved IPs ({', '.join(resolved_ips)}) probe {waf_name} edge proxies, "
                "not the internal application origin server!"
            )

        return {
            "target": self.target,
            "domain": self.domain,
            "resolved_ips": resolved_ips,
            "has_waf": waf_detected,
            "waf_name": waf_name if waf_detected else "None",
            "is_edge_proxy": waf_detected,
            "confidence": "CONFIRMED" if waf_detected else "NONE",
            "indicators": matched_indicators,
            "warning": warning_msg,
            "timestamp": datetime.now().isoformat(),
        }

    def find_origin_candidates(self) -> list[dict[str, Any]]:
        """
        Passive Origin Server Leakage Audit.
        
        Scans DNS MX records, SPF TXT records, and common unproxied subdomains
        (mail, direct, origin, ftp, cpanel) to discover non-WAF backend IP addresses.
        """
        if validate_ip(self.domain) or self.domain in ("localhost", "127.0.0.1"):
            return []

        logger.info(f"Auditing DNS records of '{self.domain}' for unproxied origin IP leakage...")
        candidates: list[OriginCandidate] = []
        seen_ips: set[str] = set(self.resolve_target_ips())

        # 1. Inspect MX Records
        try:
            from phantom_recon.core.dns_enum import DNSEnumerator
            dns_enum = DNSEnumerator(domain=self.domain, timeout=self.timeout)
            mx_records = dns_enum.enumerate_type("MX")
            for mx in mx_records:
                mx_host = mx.get("exchange", mx.get("value", "")).strip().rstrip(".")
                try:
                    mx_ip = socket.gethostbyname(mx_host)
                    if not is_routable_public_ip(mx_ip):
                        continue
                    is_waf, provider = self.is_ip_in_waf_cidr(mx_ip)
                    if mx_ip not in seen_ips:
                        seen_ips.add(mx_ip)
                        candidates.append(OriginCandidate(
                            ip=mx_ip,
                            hostname=mx_host,
                            source=f"DNS MX Record ({mx_host})",
                            is_waf_ip=is_waf,
                            waf_provider=provider,
                            evidence=f"MX host {mx_host} resolves to {mx_ip}" + (f" (Protected by {provider})" if is_waf else " (DIRECT IP, NOT BEHIND WAF)"),
                        ))
                except (socket.gaierror, OSError):
                    pass
        except Exception:
            pass

        # 2. Inspect SPF ip4: Directives in TXT Records
        try:
            txt_records = dns_enum.enumerate_type("TXT")
            for rec in txt_records:
                val = rec.get("value", "").strip("\"'")
                if val.startswith("v=spf1"):
                    # Find all ip4: entries
                    ip4_matches = re.findall(r"ip4:([0-9\.\/]+)", val)
                    for ip4_str in ip4_matches:
                        clean_ip = ip4_str.split("/")[0]
                        if validate_ip(clean_ip) and is_routable_public_ip(clean_ip) and clean_ip not in seen_ips:
                            seen_ips.add(clean_ip)
                            is_waf, provider = self.is_ip_in_waf_cidr(clean_ip)
                            candidates.append(OriginCandidate(
                                ip=clean_ip,
                                hostname=self.domain,
                                source="SPF TXT Record (ip4)",
                                is_waf_ip=is_waf,
                                waf_provider=provider,
                                evidence=f"SPF record explicitly publishes ip4:{ip4_str}" + (f" ({provider})" if is_waf else " (Direct infrastructure IP)"),
                            ))
        except Exception:
            pass

        # 3. Check Common Unproxied Subdomains
        unproxied_subdomains = [
            "mail", "direct", "origin", "ftp", "cpanel", "direct-connect",
            "server", "webmail", "backend", "admin", "dev", "vpn"
        ]
        for sub in unproxied_subdomains:
            test_host = f"{sub}.{self.domain}"
            try:
                sub_ip = socket.gethostbyname(test_host)
                if is_routable_public_ip(sub_ip) and sub_ip not in seen_ips:
                    seen_ips.add(sub_ip)
                    is_waf, provider = self.is_ip_in_waf_cidr(sub_ip)
                    candidates.append(OriginCandidate(
                        ip=sub_ip,
                        hostname=test_host,
                        source=f"Subdomain DNS: {test_host}",
                        is_waf_ip=is_waf,
                        waf_provider=provider,
                        evidence=f"{test_host} resolves to {sub_ip}" + (f" ({provider})" if is_waf else " (Unproxied host, potential origin!)"),
                    ))
            except (socket.gaierror, OSError):
                continue

        return [c.to_dict() for c in candidates]

    def run_full_waf_analysis(self) -> dict[str, Any]:
        """
        Execute comprehensive WAF detection and origin exposure audit.
        """
        waf_info = self.detect_waf()
        origin_candidates = self.find_origin_candidates()

        unprotected_candidates = [c for c in origin_candidates if not c.get("is_waf_ip")]

        waf_info["origin_leakage"] = {
            "audited": True,
            "total_candidates_found": len(origin_candidates),
            "unprotected_origin_candidates": unprotected_candidates,
            "leakage_detected": bool(unprotected_candidates and waf_info.get("has_waf")),
        }

        return waf_info
